### ISSUE TITLE
Redmine 2.1.2 - Juno 4.2 SR1 - redmine_mylyn_connector - 2.8.2.stable - NoMethodError (undefined method `returning')

### ISSUE THREAD

**Issue by a-herbe** [danmunn/redmine_mylyn_connector#9]
Hi,

Thanks for your work ans time spent.

I'm testing migration from Redmine 1.3.3 to 2.1.2 (seems a lot of works (Number of plugins need to be rewritten).

With redmine_mylyn_connector, I'v got this error (with thin app server) :

Started GET "/mylyn/issues?key=96647d3d46cf77c9223745baa77f67b806e4d4c1&fields%5B%5D=status_id&operators%5Bstatus_id%5D=o&values%5Bstatus_id%5D%5B5D=&fields%5B%5D=assigned_to_id&operators%5Bassigned_to_id%5D=%3D&values%5Bassigned_to_id%5D%5B%5D=me" for 127.0.0.1 at 2012-10-18 19:00:23 +0200
Processing by MylynConnector::IssuesController#index as XML
  Parameters: {"key"=>"96647d3d46cf77c9223745baa77f67b806e4d4c1", "fields"=>["st
atus_id", "assigned_to_id"], "operators"=>{"status_id"=>"o", "assigned_to_id"=>"
="}, "values"=>{"status_id"=>[""], "assigned_to_id"=>["me"]}}
 Current user: a-herbe (id=3)
Completed 500 Internal Server Error in 125ms

NoMethodError (undefined method `returning' for #<Query:0x559d7a8>):
  app/models/query.rb:436:in`groupable_columns'
  app/models/query.rb:518:in `group_by_column'
  app/models/query.rb:514:in`grouped?'
  app/models/query.rb:505:in `group_by_sort_order'
  app/models/query.rb:625:in`issues'

I've you any idea or patch to fix it qeekly ?

**Comment by a-herbe** [comment]
It seems a consequence of an other plugin, because now it works fine with Redmine 2.1.2 - Juno 4.2 SR1 - redmine_mylyn_connector - 2.8.2.stable.
